language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cppcheck
  - mkdir build
  - cd build
  - cmake ..

script:
  - sysctl -w net.ipv4.ping_group_range="0 0"
  - make
  - sudo ./test/TestAll
  - cppcheck --error-exitcode=1 --enable=style,performance,information ../src -I ../src